config/routes.rb
WeddingWebsite::Application.routes.draw do
  resources :invitations

  resources :guests

  match '/hotels' => 'static_pages#hotels'
  match '/schedule' => 'static_pages#schedule'
  match '/directions' => 'static_pages#directions'
  match '/registry' => 'static_pages#registry'
  match '/home' => 'static_pages#home'

  root :to => 'static_pages#home'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  attr_accessible :address, :first_name, :invite_id, :last_name
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  attr_accessible :address, :attending, :song_suggestion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guests }
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
    @guest = Guest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/new
  # GET /guests/new.json
  def new
    @guest = Guest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/1/edit
  def edit
    @guest = Guest.find(params[:id])
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(params[:guest])

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render json: @guest, status: :created, location: @guest }
      else
        format.html { render action: "new" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guests/1
  # PUT /guests/1.json
  def update
    @guest = Guest.find(params[:id])

    respond_to do |format|
      if @guest.update_attributes(params[:guest])
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to guests_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invitations }
    end
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/new
  # GET /invitations/new.json
  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/1/edit
  def edit
    @invitation = Invitation.find(params[:id])
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = Invitation.new(params[:invitation])

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation, notice: 'Invitation was successfully created.' }
        format.json { render json: @invitation, status: :created, location: @invitation }
      else
        format.html { render action: "new" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invitations/1
  # PUT /invitations/1.json
  def update
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      if @invitation.update_attributes(params[:invitation])
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to invitations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def hotels
  end

  def schedule
  end

  def directions
  end

  def registry
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :invite_id %><br />
    <%= f.number_field :invite_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<h1>Listing guests</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Invite</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guests.each do |guest| %>
  <tr>
    <td><%= guest.first_name %></td>
    <td><%= guest.last_name %></td>
    <td><%= guest.invite_id %></td>
    <td><%= guest.address %></td>
    <td><%= link_to 'Show', guest %></td>
    <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
    <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @guest.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @guest.last_name %>
</p>

<p>
  <b>Invite:</b>
  <%= @guest.invite_id %>
</p>

<p>
  <b>Address:</b>
  <%= @guest.address %>
</p>


<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :song_suggestion %><br />
    <%= f.text_field :song_suggestion %>
  </div>
  <div class="field">
    <%= f.label :attending %><br />
    <%= f.check_box :attending %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Song suggestion</th>
    <th>Attending</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.address %></td>
    <td><%= invitation.song_suggestion %></td>
    <td><%= invitation.attending %></td>
    <td><%= link_to 'Show', invitation %></td>
    <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
    <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @invitation.address %>
</p>

<p>
  <b>Song suggestion:</b>
  <%= @invitation.song_suggestion %>
</p>

<p>
  <b>Attending:</b>
  <%= @invitation.attending %>
</p>


<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>

app/views/layouts/_flash.html.haml
#flash

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }
%title= @title || 'Julia and Max\'s wedding'
%meta{ :content => @description || 'Our nuptuals', :name => 'description'}
= stylesheet_link_tag "application", :media => "all"
= javascript_include_tag "application"
= csrf_meta_tag
%meta{ :content => 'Max', :name => 'author' }

app/views/layouts/_nav.html.haml
%ul 
  %li
    = link_to '/hotels', :class => 'navitem' do
      = image_tag("suitcase1.png", :class => 'placeholder', :height => '32px')
      = image_tag("feet.png", :class => 'mouseover', :height => '32px')
      %br
      %span.navitemtext HOTELS
  %li
    = link_to '/schedule', :class => 'navitem' do
      = image_tag("calendar.png", :class => 'placeholder', :height => '32px')
      = image_tag("feet.png", :class => 'mouseover', :height => '32px')
      %br
      %span.navitemtext SCHEDULE

  %li 
    = link_to '/directions', :class => 'navitem' do
      = image_tag("signpost.png", :class => 'placeholder', :height => '32px')
      = image_tag("feet.png", :class => 'mouseover', :height => '32px')
      %br
      %span.navitemtext DIRECTIONS 

  %li
    = link_to '/rsvp', :class => 'navitem' do
      = image_tag("mail.png", :class => 'placeholder', :height => '32px')
      = image_tag("feet.png", :class => 'mouseover', :height => '32px')
      %br
      %span.navitemtext RSVP 
  %li
    = link_to '/registry', :class => 'navitem' do
      = image_tag("shoppingcart.png", :class => 'placeholder', :height => '32px')
      = image_tag("feet.png", :class => 'mouseover', :height => '32px')
      %br
      %span.navitemtext REGISTRY

app/views/layouts/application.html.haml
<!DOCTYPE html>

%html{ :lang => 'en' }
  %head
    =render 'layouts/head'
  %body.plain
    #page
      #header
        =link_to root_path do 
          = image_tag 'header_image.png', :alt => 'IN HOLY MATRIMONY'
      #navigation
        =render 'layouts/nav'
      =image_tag("hdiv.png", :class => "hdiv" )
      #content 
        = render :partial => 'layouts/flash', :locals => { :flash => flash }
        = yield
      
      =image_tag("hdiv.png", :class => "hdiv" )
      #footer
        %ul
          %li= 'Thanks to Grace for Graphic design'
          %li= 'Website created by Max Kuipers'

app/views/static_pages/directions.html.erb
<h1>StaticPages#directions</h1>
<p>Find me in app/views/static_pages/directions.html.erb</p>

app/views/static_pages/home.html.haml
.maxjulia= image_tag 'savethedate.jpg', :height => '60%', :width => '60%'

app/views/static_pages/hotels.html.erb
<h1>StaticPages#hotels</h1>
<p>Find me in app/views/static_pages/hotels.html.erb</p>

app/views/static_pages/registry.html.erb
<h1>StaticPages#registry</h1>
<p>Find me in app/views/static_pages/registry.html.erb</p>

app/views/static_pages/schedule.html.erb
<h1>StaticPages#schedule</h1>
<p>Find me in app/views/static_pages/schedule.html.erb</p>